### PR TITLE
[DSCP-142] [DSCP-459] Add sorting to API

### PR DESCRIPTION
**Pull request by Martoon-00**
### Description

This PR consists of 3 parts:
1. `SortingParams` Servant API combinator which makes an endpoint optionally accept sorting specification and provide the corresponding object of `SortingSpec` type to an endpoint implementation. See `Dscp/Util/Servant.hs`.
2. `SortingSpec` mapping to an ordering thing understandable by Beam. See `Dscp/DB/SQLite/ApiUtil.hs`.
3. Introduce this all to Student API.

I'm not sure which kind of tests would be appropriate here, probably we'd better create a ticket to QA team? Or, we can wait till #353 is merged.

**For future work:**
* DSCP-425: allow to specify nulls-first / nulls-last order - but not earlier than we move to Postgres.
* Do a similar thing for filters, so that all filters would be passed as a single parameter (no more countless `sGetAssignments Nothing Nothing Nothing` in tests, no more need to define `EducatorGetAssugnmentsFilters` datatypes, generic filters (`==`, comparisons, `like` statements e.t.c)). DSCP-434.

**Potential problems:**
* Not clear how pagination will couple with sorting. Simple `offset/limit` pagination remains easy to implement, but we will probably want to use keyset (`nextId/limit`) pagination in most cases instead and here sorting breaks things unless special care is taken.

### YT issue

https://issues.serokell.io/issue/DSCP-142

### Checklist

Hint: a perfect PR has all the checkmarks set.

Possible related changes (conditional):
- [ ] I added tests if required, in case they are:
  - Covering new introduced functionality (feature).
  - Regression tests preventing the bug from silently reappearing again (bugfix).
- [x] I have checked the [sample config](../tree/master/docs/config-full-sample.yaml) and [launch scripts](../tree/master/scripts/launch) and updated them if it was necessary (especially if executables or CLIs were changed).
- [x] I have checked READMEs and changed them accordingly if it's necessary (the main [README.md](../tree/master/README.md) as well as subproject READMEs for all related executables).
- [x] If a public API structure or/and data serialization was changed, I made sure that these changes are reflected in the:
  - [Swagger](../tree/master/specs/disciplina) API specs.
  - Any [related documentation](../tree/master/docs/api-types.md).
- [x] If any public documentation was written, I have spellchecked it.

Stylistic (obligatory):
- [x] My commit history is clean, descriptive and do not contain merge or revert commits or commits like "WIP".
- [x] My code complies with the [style guide](../tree/master/docs/code-style.md).
- [x] My code is documented (haddock) and these docs are decent (full enough and spellchecked).

### CODE REVIEW

**Comment by yorickvP** [comment]
HList has a really old `Setup.lhs` file, that is not compatible with cabal 2. Stack ignores the `Setup.lhs` file and just runs `cabal configure`.

default.nix:
```nix
stackToNix {
# ...
overrides = self: super: {
  HList = pkgs.haskell.lib.overrideCabal super.HList (o: {
    preCompileBuildDriver = ''
      rm -f Setup.lhs Setup.hs
      cat << EOF > Setup.hs
      import Distribution.Simple
      main = defaultMain
      EOF
    '';
  });
};
}
```

**Comment by Martoon-00** [comment]
Thanks!

**Comment by Martoon-00** [comment]
Created DSCP-459 for extraction to a library.

> Can we do it in a more lightweight way?
:thinking: :thinking: :thinking: 
Megaparsec allows to easily achieve decent parsing errors, not saying about readable code. And actually, I counted on that some paring library will be used for other purposes as well sooner or later.
On the other side, if I extract this code to another library, it would be very weird to have such a dependency.
Maybe let me rewrite this code after I do DSCP-459 so that I don't litter Disciplina project with tests?

**Comment by flyingleafe** [comment]
@Martoon-00 let's just do it then, and this PR will contain only the import of the lib and its application, together with removal of `Dscp.Util.Servant`

**Comment by Martoon-00** [comment]
:tada: Celebrating the hoursewarming :tada:
https://github.com/serokell/servant-util

**Pull request merged**
