### PR TITLE
[SRK-3] Eliminate need in specifying YT ticket in PR

### PR DESCRIPTION
**Pull request by Martoon-00**
### Description

What about using a script which renders a ticket id into YT link on itself?
One for Tampermonkey: https://gist.github.com/Martoon-00/9566df26317e2aecfa5af9f763662829

screenshot from 2018-11-12 21-00-18

### YT issue

https://issues.serokell.io/issue/SRK-3

### Checklist

Hint: a perfect PR has all the checkmarks set.

Possible related changes (conditional):
- [x] I added tests if required, in case they are:
  - Covering new introduced functionality (feature).
  - Regression tests preventing the bug from silently reappearing again (bugfix).
- [x] I have checked the [sample config](../tree/master/docs/config-full-sample.yaml) and [launch scripts](../tree/master/scripts/launch) and updated them if it was necessary (especially if executables or CLIs were changed).
- [x] I have checked READMEs and changed them accordingly if it's necessary (the main [README.md](../tree/master/README.md) as well as subproject READMEs for all related executables).
- [x] If a public API structure or/and data serialization was changed, I made sure that these changes are reflected in the:
  - [Swagger](../tree/master/specs/disciplina) API specs.
  - Any [related documentation](../tree/master/docs/api-types.md).
- [x] If any public documentation was written, I have spellchecked it.

Stylistic (obligatory):
- [x] My commit history is clean, descriptive and do not contain merge or revert commits or commits like "WIP".
- [x] My code complies with the [style guide](../tree/master/docs/code-style.md).
- [x] My code is documented (haddock) and these docs are decent (full enough and spellchecked).

### CODE REVIEW

**Comment by goodsoft** [comment]
There's also e-mail, so pleasr no.

**Comment by Martoon-00** [comment]
What do you mean?
You get e-mail notifications containing the full PR content and want them to contain a link to the ticket?

**Comment by flyingleafe** [comment]
I don't use user scripts in my browser, and I doubt the majority of us do. Thanks for sharing, but we cannot enforce the adoption of this stuff.

**Comment by flyingleafe** [comment]
@Martoon-00 I think this PR should be closed. Next time better start a discussion in the chat on the matter before actually doing stuff.

**Pull request closed without merging**
