### PR TITLE
[LTB-52] Bump lootbox with simpler `HasLens`

### PR DESCRIPTION
**Pull request by Martoon-00**
### Description

Where there is no need to specify a tag anymore.
Although now instead of `lensOf @a` you have to write `lensOf @_ @a`, which is the case
in a few places.

This all is arguable, the more people express their concerns the better the overall result
will be.

**Before merge:**
- [ ] Depend on lootbox commit in master.
- [ ] Depend on blockchain-util commit in a reasonable branch.

### YT issue

https://issues.serokell.io/issue/LTB-52

### Checklist

Hint: a perfect PR has all the checkmarks set.

Possible related changes (conditional):
- [x] I added tests if required, in case they are:
  - Covering new introduced functionality (feature).
  - Regression tests preventing the bug from silently reappearing again (bugfix).
- [x] I have checked the [sample config](../tree/master/docs/config-full-sample.yaml) and [launch scripts](../tree/master/scripts/launch) and updated them if it was necessary (especially if executables or CLIs were changed).
- [x] I have checked READMEs and changed them accordingly if it's necessary (the main [README.md](../tree/master/README.md) as well as subproject READMEs for all related executables).
- [x] If a public API structure or/and data serialization was changed, I made sure that these changes are reflected in the:
  - [Swagger](../tree/master/specs/disciplina) API specs.
  - Any [related documentation](../tree/master/docs/api-types.md).
- [x] If any public documentation was written, I have spellchecked it.

Stylistic (obligatory):
- [x] My commit history is clean, descriptive and do not contain merge or revert commits or commits like "WIP".
- [x] My code complies with the [style guide](../tree/master/docs/code-style.md).
- [x] My code is documented (haddock) and these docs are decent (full enough and spellchecked).

### CODE REVIEW

**Comment by Martoon-00** [comment]
No (
I'm a bit scared of flipping arguments in `HasLens` typeclass declaration, one guy can punish me for that later. Although If someone else suggests that, I will be able to tell that we took a decision as a team )

**Comment by Martoon-00** [comment]
Weeell, that's a fair point. I also felt uncomfortable with adding extra `@_` or removing type annotations completely.

**Comment by flyingleafe** [comment]
@Martoon-00 okay what are we gonna do with that PR?

**Comment by Martoon-00** [comment]
There is an option to replace `class HasLens s a` with `class HasLens a s` in lootbox, this will give us `lensOf` with desired order of type arguments. If you consider this as a worth change, then I will have enough votes to do it.
If not, I will close this PR.

**Comment by flyingleafe** [comment]
@Martoon-00 nah, let's close

**Pull request closed without merging**
